name: plaid
channels:
  - defaults
dependencies:
  - h5py=3.7.*
  - jupyter=1.0.*
  - matplotlib=3.6.*
  - numba=0.56.*
  - numpy=1.23.*
  - pandas=1.5.*
  - pip=22.3.*
  - python=3.10.*
  - scikit-learn=1.2.*
  - scipy=1.9.*
  - seaborn=0.12.*
  - pytables=3.7.*
  - pip:
      - qtconsole=5.4.*
      - tensorflow=2.13.*
